# site settings

title:          JoWeb
tagline:        Un peu de Jo, beaucoup de web
url:            https://github.com/j0web/ovh # https://cvless.netlify.app
baseurl:        "/"
permalink:      pretty
repo:           # https://github.com/j0web/ovh

# author settings

author:
  name:         Joachim
  email:        dev@joweb.ovh
photo:          # /assets/photo.jpg

# build settings

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - .git
  - .jekyll-cache
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor

sass:
  sass_dir:     _sass
  sourcemap:    never

feed:
  path:         atom.xml

autopages:
  enabled:      false

pagination:
  enabled:      true
  per_page:     1
  sort_reverse: true
  permalink:    /:num/
  title:        ":title &middot; Page :num"
