# site settings

title:          Jo, etc.
tagline:        Jo et caetera.
url:            https://et-caetera.xyz # https://cvless.netlify.app
baseurl:        ""
permalink:      pretty
repo:           https://github.com/et-caetera/et-caetera.github.io # https://github.com/username/username.github.io

# author settings

author:
  name:         Jo
  email:        jo@et-caetera.xyz
photo:          # /assets/photo.jpg

# build settings

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - .git
  - .jekyll-cache
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor

sass:
  sass_dir:     _sass
  sourcemap:    never

feed:
  path:         atom.xml

autopages:
  enabled:      false

pagination:
  enabled:      true
  per_page:     1
  sort_reverse: true
  permalink:    /:num/
  title:        ":title &middot; Page :num"
