# site settings

title:          Geek Fr
tagline:        La liberté est intimement liée à la connaissance. En France, elle est accessible au plus grand nombre car majoritairement gratuite. Profitez-en carvous ne pouvez compter qur sur vous-même pour changer votre vie. Personne d'autre ne le fera pour vous !
url:            https:/geekfr.github.io
baseurl:        ""
permalink:      pretty
repo:           https://github.com/geekfr/geekfr.github.io # https://github.com/username/username.github.io

# author settings

author:
  name:         Jo
  email:        jomd@duck.com
photo:          # /assets/photo.jpg

# build settings

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - .git
  - .jekyll-cache
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor

sass:
  sass_dir:     _sass
  sourcemap:    never

feed:
  path:         atom.xml

autopages:
  enabled:      false

pagination:
  enabled:      true
  per_page:     1
  sort_reverse: true
  permalink:    /:num/
  title:        ":title &middot; Page :num"
